### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ZenkiWeW** [vikmeup/SCLAlertView-Swift#106]
i'm new in ios development and i don't have any idea about pod. is there any way to use your library in my project. thanks a lot

**Comment by samueljrains** [comment]
If you'd like to use the very helpful CocoaPods dependency manager.  Here is the homepage with install instructions https://cocoapods.org/

Otherwise, you can just copy the 'SCLAAlertView.swift' file from this repo (at: SCLAlertView-Swift/SCLAlertView/SCLAlertView.swift) into your Swift project and call it within your project from there.

**Comment by vikmeup** [comment]
Thanks @samueljrains.
