### ISSUE TITLE
Change default button text

### ISSUE THREAD

**Issue by mehmetvefa** [vikmeup/SCLAlertView-Swift#70]
How can I change default button text? I am using default alert and I have a **DONE** button.

```
let alertview : SCLAlertViewResponder = SCLAlertView().showError( "Hata!", subTitle: "Lütfen bilgilerinizi kontrol edin." )
```

I want to change this button text without add any more button.

**Comment by ncerezo** [comment]
If you Cmd+Click in the showError function in XCode it will take you to the function declaration.
There you can see that it takes up to 4 parameters, being the last two optionals.
So you can simply call it like:

```swift
let alertView = SCLAlertView().showError( "Hata!", subTitle: "Lütfen bilgilerinizi kontrol edin.", closeButtonTitle: "What ever you wish" )
```

It's really a good practice to take a look at the source code when in doubt, since you have access to it :)
